language: node_js
node_js:
    - "node"
script:
    - echo 'Building https://jacekkosciesza.com'
    - npm run build
install:
    - npm install
    - npm install -g firebase-tools
after_success:
    - echo 'Deploying https://jacekkosciesza.com to Firebase'
    - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}