language: node_js
node_js:
    - "node"
sudo: required
dist: trusty
branches:
  only:
    - master
before_install:
    - cd ./frontend/platform
install:
    - npm install
before_script:
    - npm install -g lighthouse
    - export DISPLAY=:99.0
    - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
    - sh -e /etc/init.d/xvfb start
    - npm explore -g lighthouse -- ./lighthouse-core/scripts/download-chrome.sh
    - mv $(npm root -g)/lighthouse/chrome-linux .
    - $LIGHTHOUSE_CHROMIUM_PATH --version
    - chmod u+x start-server.sh
script:
    - npm run build
    - ./start-server.sh
    - npm run lighthouse
after_success:
    - firebase deploy --token=${FIREBASE_API_TOKEN}