language: node_js
node_js:
    - "node"
branches:
  only:
    - master
script:
    - echo 'Building https://jacekkosciesza.com'
    - npm run build
install:
    - npm install
    - npm install -g firebase-tools
after_success:
    - echo 'Deploying https://jacekkosciesza.com to Firebase'
    - firebase deploy --token=${FIREBASE_API_TOKEN}